title: 古月的个人博客
description: 记录科研、阅读、生活与思考
author:
  name: 古月
  avatar: /assets/images/20260808170010.jpg
  
theme: minima

lang: zh-CN
timezone: Asia/Shanghai

permalink: /:year/:month/:day/:title/

header_pages:
  - about.md
