title: 古月依旧照今人 | Whosocial
description: >
  种一棵树最好的时间是十年前，其次是现在。


theme: minima

lang: zh-CN
timezone: Asia/Shanghai

permalink: /:year/:month/:day/:title/

header_pages:
  - about.md
  - research.md
  - publications.md # 学者必备
  - more.md # 学者必备

minima:
  social_links:
    github: whosocial
    twitter: your_twitter_handle # 如果有的话可以加上
