title: 古月依旧照今人 | Whosocial

description: >
  Research notes on microbiology,
  bacterial adaptation and life exploration.

author:
  name: 古月
  avatar: /assets/images/20260808170010.jpg

theme: minima

lang: zh-CN
timezone: Asia/Shanghai

permalink: /:year/:month/:day/:title/

header_pages:
  - about.md
  - research.md
  - publications.md

minima:
  social_links:
    github: whosocial
